// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// AffinityV1 Affinity is a group of affinity scheduling rules.
type AffinityV1 struct {
	NodeAffinity    *NodeAffinityV1    `json:"nodeAffinity,omitempty"`
	PodAffinity     *PodAffinityV1     `json:"podAffinity,omitempty"`
	PodAntiAffinity *PodAntiAffinityV1 `json:"podAntiAffinity,omitempty"`
}
