// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ContainerStateV1 ContainerState holds a possible state of container. Only one of its members may be specified. If none of them is specified, the default one is ContainerStateWaiting.
type ContainerStateV1 struct {
	Running    *ContainerStateRunningV1    `json:"running,omitempty"`
	Terminated *ContainerStateTerminatedV1 `json:"terminated,omitempty"`
	Waiting    *ContainerStateWaitingV1    `json:"waiting,omitempty"`
}
