// Code generated by pk8s; DO NOT EDIT.

package k8s

// CustomResourceDefinitionV1 CustomResourceDefinition represents a resource that should be exposed on the API server.  Its name MUST be in the format <.spec.name>.<.spec.group>.
type CustomResourceDefinitionV1 struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`
	// ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
	Metadata *ObjectMetaV1 `json:"metadata,omitempty"`
	// CustomResourceDefinitionSpec describes how a user wants their resource to appear
	Spec CustomResourceDefinitionSpecV1 `json:"spec"`
	// CustomResourceDefinitionStatus indicates the state of the CustomResourceDefinition
	Status *CustomResourceDefinitionStatusV1 `json:"status,omitempty"`
}
