// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// CustomResourceValidationV1 CustomResourceValidation is a list of validation methods for CustomResources.
type CustomResourceValidationV1 struct {
	OpenAPIV3Schema *JSONSchemaPropsV1 `json:"openAPIV3Schema,omitempty"`
}
