// Code generated by pk8s; DO NOT EDIT.

package k8s

// DaemonEndpointV1 DaemonEndpoint contains information about a single Daemon endpoint.
type DaemonEndpointV1 struct {
	// Port number of the given endpoint.
	Port int32 `json:"Port"`
}
