// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// DaemonSetSpecV1 DaemonSetSpec is the specification of a daemon set.
type DaemonSetSpecV1 struct {
	// The minimum number of seconds for which a newly created DaemonSet pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready).
	MinReadySeconds *int32 `json:"minReadySeconds,omitempty"`
	// The number of old history to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10.
	RevisionHistoryLimit *int32                     `json:"revisionHistoryLimit,omitempty"`
	Selector             LabelSelectorV1            `json:"selector"`
	Template             PodTemplateSpecV1          `json:"template"`
	UpdateStrategy       *DaemonSetUpdateStrategyV1 `json:"updateStrategy,omitempty"`
}
