// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// EnvVarSourceV1 EnvVarSource represents a source for the value of an EnvVar.
type EnvVarSourceV1 struct {
	ConfigMapKeyRef  *ConfigMapKeySelectorV1  `json:"configMapKeyRef,omitempty"`
	FieldRef         *ObjectFieldSelectorV1   `json:"fieldRef,omitempty"`
	ResourceFieldRef *ResourceFieldSelectorV1 `json:"resourceFieldRef,omitempty"`
	SecretKeyRef     *SecretKeySelectorV1     `json:"secretKeyRef,omitempty"`
}
