// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// EnvFromSourceV1 EnvFromSource represents the source of a set of ConfigMaps
type EnvFromSourceV1 struct {
	ConfigMapRef *ConfigMapEnvSourceV1 `json:"configMapRef,omitempty"`
	// An optional identifier to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER.
	Prefix    *string            `json:"prefix,omitempty"`
	SecretRef *SecretEnvSourceV1 `json:"secretRef,omitempty"`
}
