// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// EphemeralVolumeSourceV1 Represents an ephemeral volume that is handled by a normal storage driver.
type EphemeralVolumeSourceV1 struct {
	VolumeClaimTemplate *PersistentVolumeClaimTemplateV1 `json:"volumeClaimTemplate,omitempty"`
}
