// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ExternalMetricStatusV2 ExternalMetricStatus indicates the current value of a global metric not associated with any Kubernetes object.
type ExternalMetricStatusV2 struct {
	Current MetricValueStatusV2 `json:"current"`
	Metric  MetricIdentifierV2  `json:"metric"`
}
