// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ExternalDocumentationV1 ExternalDocumentation allows referencing an external resource for extended documentation.
type ExternalDocumentationV1 struct {
	Description *string `json:"description,omitempty"`
	Url         *string `json:"url,omitempty"`
}
