// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// GroupVersionResourceV1alpha1 The names of the group, the version, and the resource.
type GroupVersionResourceV1alpha1 struct {
	// The name of the group.
	Group *string `json:"group,omitempty"`
	// The name of the resource.
	Resource *string `json:"resource,omitempty"`
	// The name of the version.
	Version *string `json:"version,omitempty"`
}
