// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// HostIPV1 HostIP represents a single IP address allocated to the host.
type HostIPV1 struct {
	// IP is the IP address assigned to the host
	Ip *string `json:"ip,omitempty"`
}
