// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// IngressBackendV1 IngressBackend describes all endpoints for a given service and port.
type IngressBackendV1 struct {
	Resource *TypedLocalObjectReferenceV1 `json:"resource,omitempty"`
	Service  *IngressServiceBackendV1     `json:"service,omitempty"`
}
