// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// IngressStatusV1 IngressStatus describe the current state of the Ingress.
type IngressStatusV1 struct {
	LoadBalancer *IngressLoadBalancerStatusV1 `json:"loadBalancer,omitempty"`
}
