// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// IPAddressSpecV1alpha1 IPAddressSpec describe the attributes in an IP Address.
type IPAddressSpecV1alpha1 struct {
	ParentRef ParentReferenceV1alpha1 `json:"parentRef"`
}
