// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

import (
	"time"
)

// LeaseSpecV1 LeaseSpec is a specification of a Lease.
type LeaseSpecV1 struct {
	// MicroTime is version of Time with microsecond level precision.
	AcquireTime *time.Time `json:"acquireTime,omitempty"`
	// holderIdentity contains the identity of the holder of a current lease.
	HolderIdentity *string `json:"holderIdentity,omitempty"`
	// leaseDurationSeconds is a duration that candidates for a lease need to wait to force acquire it. This is measure against time of last observed renewTime.
	LeaseDurationSeconds *int32 `json:"leaseDurationSeconds,omitempty"`
	// leaseTransitions is the number of transitions of a lease between holders.
	LeaseTransitions *int32 `json:"leaseTransitions,omitempty"`
	// MicroTime is version of Time with microsecond level precision.
	RenewTime *time.Time `json:"renewTime,omitempty"`
}
