// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// LifecycleV1 Lifecycle describes actions that the management system should take in response to container lifecycle events. For the PostStart and PreStop lifecycle handlers, management of the container blocks until the action is complete, unless the container process fails, in which case the handler is aborted.
type LifecycleV1 struct {
	PostStart *LifecycleHandlerV1 `json:"postStart,omitempty"`
	PreStop   *LifecycleHandlerV1 `json:"preStop,omitempty"`
}
