// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// LifecycleHandlerV1 LifecycleHandler defines a specific action that should be taken in a lifecycle hook. One and only one of the fields, except TCPSocket must be specified.
type LifecycleHandlerV1 struct {
	Exec      *ExecActionV1      `json:"exec,omitempty"`
	HttpGet   *HTTPGetActionV1   `json:"httpGet,omitempty"`
	Sleep     *SleepActionV1     `json:"sleep,omitempty"`
	TcpSocket *TCPSocketActionV1 `json:"tcpSocket,omitempty"`
}
