// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// LocalObjectReferenceV1 LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.
type LocalObjectReferenceV1 struct {
	// Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
}
