// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// MetricSpecV2 MetricSpec specifies how to scale based on a single metric (only `type` and one other matching field should be set at once).
type MetricSpecV2 struct {
	ContainerResource *ContainerResourceMetricSourceV2 `json:"containerResource,omitempty"`
	External          *ExternalMetricSourceV2          `json:"external,omitempty"`
	Object            *ObjectMetricSourceV2            `json:"object,omitempty"`
	Pods              *PodsMetricSourceV2              `json:"pods,omitempty"`
	Resource          *ResourceMetricSourceV2          `json:"resource,omitempty"`
	// type is the type of metric source.  It should be one of \"ContainerResource\", \"External\", \"Object\", \"Pods\" or \"Resource\", each mapping to a matching field in the object. Note: \"ContainerResource\" type is available on when the feature-gate HPAContainerMetrics is enabled
	Type string `json:"type"`
}
