// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// NamedResourcesStringSliceV1alpha2 NamedResourcesStringSlice contains a slice of strings.
type NamedResourcesStringSliceV1alpha2 struct {
	// Strings is the slice of strings.
	Strings []string `json:"strings"`
}
