// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// NamedResourcesResourcesV1alpha2 NamedResourcesResources is used in ResourceModel.
type NamedResourcesResourcesV1alpha2 struct {
	// The list of all individual resources instances currently available.
	Instances []NamedResourcesInstanceV1alpha2 `json:"instances"`
}
