// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// NamedResourcesIntSliceV1alpha2 NamedResourcesIntSlice contains a slice of 64-bit integers.
type NamedResourcesIntSliceV1alpha2 struct {
	// Ints is the slice of 64-bit integers.
	Ints []int64 `json:"ints"`
}
