// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// NamedResourcesInstanceV1alpha2 NamedResourcesInstance represents one individual hardware instance that can be selected based on its attributes.
type NamedResourcesInstanceV1alpha2 struct {
	// Attributes defines the attributes of this resource instance. The name of each attribute must be unique.
	Attributes []NamedResourcesAttributeV1alpha2 `json:"attributes,omitempty"`
	// Name is unique identifier among all resource instances managed by the driver on the node. It must be a DNS subdomain.
	Name string `json:"name"`
}
