// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// NetworkPolicyPeerV1 NetworkPolicyPeer describes a peer to allow traffic to/from. Only certain combinations of fields are allowed
type NetworkPolicyPeerV1 struct {
	IpBlock           *IPBlockV1       `json:"ipBlock,omitempty"`
	NamespaceSelector *LabelSelectorV1 `json:"namespaceSelector,omitempty"`
	PodSelector       *LabelSelectorV1 `json:"podSelector,omitempty"`
}
