// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// NodeConfigSourceV1 NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil. This API is deprecated since 1.22
type NodeConfigSourceV1 struct {
	ConfigMap *ConfigMapNodeConfigSourceV1 `json:"configMap,omitempty"`
}
