// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// NodeRuntimeHandlerFeaturesV1 NodeRuntimeHandlerFeatures is a set of runtime features.
type NodeRuntimeHandlerFeaturesV1 struct {
	// RecursiveReadOnlyMounts is set to true if the runtime handler supports RecursiveReadOnlyMounts.
	RecursiveReadOnlyMounts *bool `json:"recursiveReadOnlyMounts,omitempty"`
}
