// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// NodeRuntimeHandlerV1 NodeRuntimeHandler is a set of runtime handler information.
type NodeRuntimeHandlerV1 struct {
	Features *NodeRuntimeHandlerFeaturesV1 `json:"features,omitempty"`
	// Runtime handler name. Empty for the default runtime handler.
	Name *string `json:"name,omitempty"`
}
