// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// NodeDaemonEndpointsV1 NodeDaemonEndpoints lists ports opened by daemons running on the Node.
type NodeDaemonEndpointsV1 struct {
	KubeletEndpoint *DaemonEndpointV1 `json:"kubeletEndpoint,omitempty"`
}
