// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ObjectMetricSourceV2 ObjectMetricSource indicates how to scale on a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
type ObjectMetricSourceV2 struct {
	DescribedObject CrossVersionObjectReferenceV2 `json:"describedObject"`
	Metric          MetricIdentifierV2            `json:"metric"`
	Target          MetricTargetV2                `json:"target"`
}
