// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ObjectMetricStatusV2 ObjectMetricStatus indicates the current value of a metric describing a kubernetes object (for example, hits-per-second on an Ingress object).
type ObjectMetricStatusV2 struct {
	Current         MetricValueStatusV2           `json:"current"`
	DescribedObject CrossVersionObjectReferenceV2 `json:"describedObject"`
	Metric          MetricIdentifierV2            `json:"metric"`
}
