// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// PersistentVolumeClaimTemplateV1 PersistentVolumeClaimTemplate is used to produce PersistentVolumeClaim objects as part of an EphemeralVolumeSource.
type PersistentVolumeClaimTemplateV1 struct {
	Metadata *ObjectMetaV1               `json:"metadata,omitempty"`
	Spec     PersistentVolumeClaimSpecV1 `json:"spec"`
}
