// Code generated by pk8s; DO NOT EDIT.

package k8s

// PodIPV1 PodIP represents a single IP address allocated to the pod.
type PodIPV1 struct {
	// IP is the IP address assigned to the pod
	IP string `json:"ip"`
}
