// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// PodSchedulingGateV1 PodSchedulingGate is associated to a Pod to guard its scheduling.
type PodSchedulingGateV1 struct {
	// Name of the scheduling gate. Each scheduling gate must have a unique name field.
	Name string `json:"name"`
}
