// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// PodSchedulingContextSpecV1alpha2 PodSchedulingContextSpec describes where resources for the Pod are needed.
type PodSchedulingContextSpecV1alpha2 struct {
	// PotentialNodes lists nodes where the Pod might be able to run.  The size of this field is limited to 128. This is large enough for many clusters. Larger clusters may need more attempts to find a node that suits all pending resources. This may get increased in the future, but not reduced.
	PotentialNodes []string `json:"potentialNodes,omitempty"`
	// SelectedNode is the node for which allocation of ResourceClaims that are referenced by the Pod and that use \"WaitForFirstConsumer\" allocation is to be attempted.
	SelectedNode *string `json:"selectedNode,omitempty"`
}
