// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// PodTemplateSpecV1 PodTemplateSpec describes the data a pod should have when created from a template
type PodTemplateSpecV1 struct {
	Metadata *ObjectMetaV1 `json:"metadata,omitempty"`
	Spec     *PodSpecV1    `json:"spec,omitempty"`
}
