// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// PodSchedulingContextStatusV1alpha2 PodSchedulingContextStatus describes where resources for the Pod can be allocated.
type PodSchedulingContextStatusV1alpha2 struct {
	// ResourceClaims describes resource availability for each pod.spec.resourceClaim entry where the corresponding ResourceClaim uses \"WaitForFirstConsumer\" allocation mode.
	ResourceClaims []ResourceClaimSchedulingStatusV1alpha2 `json:"resourceClaims,omitempty"`
}
