// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// PodResourceClaimV1 PodResourceClaim references exactly one ResourceClaim through a ClaimSource. It adds a name to it that uniquely identifies the ResourceClaim inside the Pod. Containers that need access to the ResourceClaim reference it with this name.
type PodResourceClaimV1 struct {
	// Name uniquely identifies this resource claim inside the pod. This must be a DNS_LABEL.
	Name   string         `json:"name"`
	Source *ClaimSourceV1 `json:"source,omitempty"`
}
