// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// PodsMetricSourceV2 PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.
type PodsMetricSourceV2 struct {
	Metric MetricIdentifierV2 `json:"metric"`
	Target MetricTargetV2     `json:"target"`
}
