// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// PriorityLevelConfigurationSpecV1 PriorityLevelConfigurationSpec specifies the configuration of a priority level.
type PriorityLevelConfigurationSpecV1 struct {
	Exempt  *ExemptPriorityLevelConfigurationV1  `json:"exempt,omitempty"`
	Limited *LimitedPriorityLevelConfigurationV1 `json:"limited,omitempty"`
	// `type` indicates whether this priority level is subject to limitation on request execution.  A value of `\"Exempt\"` means that requests of this priority level are not subject to a limit (and thus are never queued) and do not detract from the capacity made available to other priority levels.  A value of `\"Limited\"` means that (a) requests of this priority level _are_ subject to limits and (b) some of the server's limited capacity is made available exclusively to this priority level. Required.
	Type string `json:"type"`
}
