// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// PriorityLevelConfigurationStatusV1 PriorityLevelConfigurationStatus represents the current state of a \"request-priority\".
type PriorityLevelConfigurationStatusV1 struct {
	// `conditions` is the current state of \"request-priority\".
	Conditions []PriorityLevelConfigurationConditionV1 `json:"conditions,omitempty"`
}
