// Code generated by pk8s; DO NOT EDIT.

package k8s

// PriorityLevelConfigurationStatusV1beta3 PriorityLevelConfigurationStatus represents the current state of a "request-priority".
type PriorityLevelConfigurationStatusV1beta3 struct {
	// `conditions` is the current state of "request-priority".
	Conditions []PriorityLevelConfigurationConditionV1beta3 `json:"conditions,omitempty"`
}
