// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// PriorityLevelConfigurationReferenceV1beta3 PriorityLevelConfigurationReference contains information that points to the \"request-priority\" being used.
type PriorityLevelConfigurationReferenceV1beta3 struct {
	// `name` is the name of the priority level configuration being referenced Required.
	Name string `json:"name"`
}
