// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ResourceClaimParametersV1alpha2 ResourceClaimParameters defines resource requests for a ResourceClaim in an in-tree format understood by Kubernetes.
type ResourceClaimParametersV1alpha2 struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`
	// DriverRequests describes all resources that are needed for the allocated claim. A single claim may use resources coming from different drivers. For each driver, this array has at most one entry which then may have one or more per-driver requests.  May be empty, in which case the claim can always be allocated.
	DriverRequests []DriverRequestsV1alpha2                  `json:"driverRequests,omitempty"`
	GeneratedFrom  *ResourceClaimParametersReferenceV1alpha2 `json:"generatedFrom,omitempty"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string       `json:"kind,omitempty"`
	Metadata *ObjectMetaV1 `json:"metadata,omitempty"`
	// Shareable indicates whether the allocated claim is meant to be shareable by multiple consumers at the same time.
	Shareable *bool `json:"shareable,omitempty"`
}
