// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ResourceClaimStatusV1alpha2 ResourceClaimStatus tracks whether the resource has been allocated and what the resulting attributes are.
type ResourceClaimStatusV1alpha2 struct {
	Allocation *AllocationResultV1alpha2 `json:"allocation,omitempty"`
	// DeallocationRequested indicates that a ResourceClaim is to be deallocated.  The driver then must deallocate this claim and reset the field together with clearing the Allocation field.  While DeallocationRequested is set, no new consumers may be added to ReservedFor.
	DeallocationRequested *bool `json:"deallocationRequested,omitempty"`
	// DriverName is a copy of the driver name from the ResourceClass at the time when allocation started.
	DriverName *string `json:"driverName,omitempty"`
	// ReservedFor indicates which entities are currently allowed to use the claim. A Pod which references a ResourceClaim which is not reserved for that Pod will not be started.  There can be at most 32 such reservations. This may get increased in the future, but not reduced.
	ReservedFor []ResourceClaimConsumerReferenceV1alpha2 `json:"reservedFor,omitempty"`
}
