// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ResourceClassParametersV1alpha2 ResourceClassParameters defines resource requests for a ResourceClass in an in-tree format understood by Kubernetes.
type ResourceClassParametersV1alpha2 struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`
	// Filters describes additional contraints that must be met when using the class.
	Filters       []ResourceFilterV1alpha2                  `json:"filters,omitempty"`
	GeneratedFrom *ResourceClassParametersReferenceV1alpha2 `json:"generatedFrom,omitempty"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string       `json:"kind,omitempty"`
	Metadata *ObjectMetaV1 `json:"metadata,omitempty"`
	// VendorParameters are arbitrary setup parameters for all claims using this class. They are ignored while allocating the claim. There must not be more than one entry per driver.
	VendorParameters []VendorParametersV1alpha2 `json:"vendorParameters,omitempty"`
}
