// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ResourceClassV1alpha2 ResourceClass is used by administrators to influence how resources are allocated.  This is an alpha type and requires enabling the DynamicResourceAllocation feature gate.
type ResourceClassV1alpha2 struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`
	// DriverName defines the name of the dynamic resource driver that is used for allocation of a ResourceClaim that uses this class.  Resource drivers have a unique name in forward domain order (acme.example.com).
	DriverName string `json:"driverName"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind          *string                                   `json:"kind,omitempty"`
	Metadata      *ObjectMetaV1                             `json:"metadata,omitempty"`
	ParametersRef *ResourceClassParametersReferenceV1alpha2 `json:"parametersRef,omitempty"`
	// If and only if allocation of claims using this class is handled via structured parameters, then StructuredParameters must be set to true.
	StructuredParameters *bool           `json:"structuredParameters,omitempty"`
	SuitableNodes        *NodeSelectorV1 `json:"suitableNodes,omitempty"`
}
