// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ResourceClaimTemplateSpecV1alpha2 ResourceClaimTemplateSpec contains the metadata and fields for a ResourceClaim.
type ResourceClaimTemplateSpecV1alpha2 struct {
	Metadata *ObjectMetaV1             `json:"metadata,omitempty"`
	Spec     ResourceClaimSpecV1alpha2 `json:"spec"`
}
