// Code generated by pk8s; DO NOT EDIT.

package k8s

// ResourceMetricStatusV2 ResourceMetricStatus indicates the current value of a resource metric known to Kubernetes, as specified in requests and limits, describing each pod in the current scale target (e.g. CPU or memory).  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the "pods" source.
type ResourceMetricStatusV2 struct {
	// MetricValueStatus holds the current value for a metric
	Current MetricValueStatusV2 `json:"current"`
	// name is the name of the resource in question.
	Name string `json:"name"`
}
