// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ResourceClaimSpecV1alpha2 ResourceClaimSpec defines how a resource is to be allocated.
type ResourceClaimSpecV1alpha2 struct {
	// Allocation can start immediately or when a Pod wants to use the resource. \"WaitForFirstConsumer\" is the default.
	AllocationMode *string                                   `json:"allocationMode,omitempty"`
	ParametersRef  *ResourceClaimParametersReferenceV1alpha2 `json:"parametersRef,omitempty"`
	// ResourceClassName references the driver and additional parameters via the name of a ResourceClass that was created as part of the driver deployment.
	ResourceClassName string `json:"resourceClassName"`
}
