// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ResourceClaimParametersReferenceV1alpha2 ResourceClaimParametersReference contains enough information to let you locate the parameters for a ResourceClaim. The object must be in the same namespace as the ResourceClaim.
type ResourceClaimParametersReferenceV1alpha2 struct {
	// APIGroup is the group for the resource being referenced. It is empty for the core API. This matches the group in the APIVersion that is used when creating the resources.
	ApiGroup *string `json:"apiGroup,omitempty"`
	// Kind is the type of resource being referenced. This is the same value as in the parameter object's metadata, for example \"ConfigMap\".
	Kind string `json:"kind"`
	// Name is the name of resource being referenced.
	Name string `json:"name"`
}
