// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ResourceFilterV1alpha2 ResourceFilter is a filter for resources from one particular driver.
type ResourceFilterV1alpha2 struct {
	// DriverName is the name used by the DRA driver kubelet plugin.
	DriverName     *string                       `json:"driverName,omitempty"`
	NamedResources *NamedResourcesFilterV1alpha2 `json:"namedResources,omitempty"`
}
