// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// SelfSubjectAccessReviewSpecV1 SelfSubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set
type SelfSubjectAccessReviewSpecV1 struct {
	NonResourceAttributes *NonResourceAttributesV1 `json:"nonResourceAttributes,omitempty"`
	ResourceAttributes    *ResourceAttributesV1    `json:"resourceAttributes,omitempty"`
}
