// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// SelfSubjectRulesReviewSpecV1 SelfSubjectRulesReviewSpec defines the specification for SelfSubjectRulesReview.
type SelfSubjectRulesReviewSpecV1 struct {
	// Namespace to evaluate rules for. Required.
	Namespace *string `json:"namespace,omitempty"`
}
