// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// SelfSubjectReviewStatusV1beta1 SelfSubjectReviewStatus is filled by the kube-apiserver and sent back to a user.
type SelfSubjectReviewStatusV1beta1 struct {
	UserInfo *UserInfoV1 `json:"userInfo,omitempty"`
}
