// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ServiceCIDRStatusV1alpha1 ServiceCIDRStatus describes the current state of the ServiceCIDR.
type ServiceCIDRStatusV1alpha1 struct {
	// conditions holds an array of metav1.Condition that describe the state of the ServiceCIDR. Current service state
	Conditions []ConditionV1 `json:"conditions,omitempty"`
}
