// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ServiceReferenceV1 ServiceReference holds a reference to Service.legacy.k8s.io
type ServiceReferenceV1 struct {
	// Name is the name of the service
	Name *string `json:"name,omitempty"`
	// Namespace is the namespace of the service
	Namespace *string `json:"namespace,omitempty"`
	// If specified, the port on the service that hosting webhook. Default to 443 for backward compatibility. `port` should be a valid port number (1-65535, inclusive).
	Port *int32 `json:"port,omitempty"`
}
