// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// ServiceStatusV1 ServiceStatus represents the current status of a service.
type ServiceStatusV1 struct {
	// Current service state
	Conditions   []ConditionV1         `json:"conditions,omitempty"`
	LoadBalancer *LoadBalancerStatusV1 `json:"loadBalancer,omitempty"`
}
