// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// SessionAffinityConfigV1 SessionAffinityConfig represents the configurations of session affinity.
type SessionAffinityConfigV1 struct {
	ClientIP *ClientIPConfigV1 `json:"clientIP,omitempty"`
}
