// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// SleepActionV1 SleepAction describes a \"sleep\" action.
type SleepActionV1 struct {
	// Seconds is the number of seconds to sleep.
	Seconds int64 `json:"seconds"`
}
