// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// StatefulSetUpdateStrategyV1 StatefulSetUpdateStrategy indicates the strategy that the StatefulSet controller will use to perform updates. It includes any additional parameters necessary to perform the update for the indicated strategy.
type StatefulSetUpdateStrategyV1 struct {
	RollingUpdate *RollingUpdateStatefulSetStrategyV1 `json:"rollingUpdate,omitempty"`
	// Type indicates the type of the StatefulSetUpdateStrategy. Default is RollingUpdate.
	Type *string `json:"type,omitempty"`
}
