// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// SubjectV1beta3 Subject matches the originator of a request, as identified by the request authentication system. There are three ways of matching an originator; by user, group, or service account.
type SubjectV1beta3 struct {
	Group *GroupSubjectV1beta3 `json:"group,omitempty"`
	// `kind` indicates which one of the other fields is non-empty. Required
	Kind           string                        `json:"kind"`
	ServiceAccount *ServiceAccountSubjectV1beta3 `json:"serviceAccount,omitempty"`
	User           *UserSubjectV1beta3           `json:"user,omitempty"`
}
