// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// TokenRequestV1 TokenRequest contains parameters of a service account token.
type TokenRequestV1 struct {
	// audience is the intended audience of the token in \"TokenRequestSpec\". It will default to the audiences of kube apiserver.
	Audience string `json:"audience"`
	// expirationSeconds is the duration of validity of the token in \"TokenRequestSpec\". It has the same default value of \"ExpirationSeconds\" in \"TokenRequestSpec\".
	ExpirationSeconds *int64 `json:"expirationSeconds,omitempty"`
}
