// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// VolumeProjectionV1 Projection that may be projected along with other supported volume types
type VolumeProjectionV1 struct {
	ClusterTrustBundle  *ClusterTrustBundleProjectionV1  `json:"clusterTrustBundle,omitempty"`
	ConfigMap           *ConfigMapProjectionV1           `json:"configMap,omitempty"`
	DownwardAPI         *DownwardAPIProjectionV1         `json:"downwardAPI,omitempty"`
	Secret              *SecretProjectionV1              `json:"secret,omitempty"`
	ServiceAccountToken *ServiceAccountTokenProjectionV1 `json:"serviceAccountToken,omitempty"`
}
