// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// VolumeAttachmentSpecV1 VolumeAttachmentSpec is the specification of a VolumeAttachment request.
type VolumeAttachmentSpecV1 struct {
	// attacher indicates the name of the volume driver that MUST handle this request. This is the name returned by GetPluginName().
	Attacher string `json:"attacher"`
	// nodeName represents the node that the volume should be attached to.
	NodeName string                   `json:"nodeName"`
	Source   VolumeAttachmentSourceV1 `json:"source"`
}
