// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// VolumeNodeAffinityV1 VolumeNodeAffinity defines constraints that limit what nodes this volume can be accessed from.
type VolumeNodeAffinityV1 struct {
	Required *NodeSelectorV1 `json:"required,omitempty"`
}
