// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package k8s

// VolumeV1 Volume represents a named volume in a pod that may be accessed by any container in the pod.
type VolumeV1 struct {
	AwsElasticBlockStore *AWSElasticBlockStoreVolumeSourceV1 `json:"awsElasticBlockStore,omitempty"`
	AzureDisk            *AzureDiskVolumeSourceV1            `json:"azureDisk,omitempty"`
	AzureFile            *AzureFileVolumeSourceV1            `json:"azureFile,omitempty"`
	Cephfs               *CephFSVolumeSourceV1               `json:"cephfs,omitempty"`
	Cinder               *CinderVolumeSourceV1               `json:"cinder,omitempty"`
	ConfigMap            *ConfigMapVolumeSourceV1            `json:"configMap,omitempty"`
	Csi                  *CSIVolumeSourceV1                  `json:"csi,omitempty"`
	DownwardAPI          *DownwardAPIVolumeSourceV1          `json:"downwardAPI,omitempty"`
	EmptyDir             *EmptyDirVolumeSourceV1             `json:"emptyDir,omitempty"`
	Ephemeral            *EphemeralVolumeSourceV1            `json:"ephemeral,omitempty"`
	Fc                   *FCVolumeSourceV1                   `json:"fc,omitempty"`
	FlexVolume           *FlexVolumeSourceV1                 `json:"flexVolume,omitempty"`
	Flocker              *FlockerVolumeSourceV1              `json:"flocker,omitempty"`
	GcePersistentDisk    *GCEPersistentDiskVolumeSourceV1    `json:"gcePersistentDisk,omitempty"`
	GitRepo              *GitRepoVolumeSourceV1              `json:"gitRepo,omitempty"`
	Glusterfs            *GlusterfsVolumeSourceV1            `json:"glusterfs,omitempty"`
	HostPath             *HostPathVolumeSourceV1             `json:"hostPath,omitempty"`
	Iscsi                *ISCSIVolumeSourceV1                `json:"iscsi,omitempty"`
	// name of the volume. Must be a DNS_LABEL and unique within the pod. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name                  string                               `json:"name"`
	Nfs                   *NFSVolumeSourceV1                   `json:"nfs,omitempty"`
	PersistentVolumeClaim *PersistentVolumeClaimVolumeSourceV1 `json:"persistentVolumeClaim,omitempty"`
	PhotonPersistentDisk  *PhotonPersistentDiskVolumeSourceV1  `json:"photonPersistentDisk,omitempty"`
	PortworxVolume        *PortworxVolumeSourceV1              `json:"portworxVolume,omitempty"`
	Projected             *ProjectedVolumeSourceV1             `json:"projected,omitempty"`
	Quobyte               *QuobyteVolumeSourceV1               `json:"quobyte,omitempty"`
	Rbd                   *RBDVolumeSourceV1                   `json:"rbd,omitempty"`
	ScaleIO               *ScaleIOVolumeSourceV1               `json:"scaleIO,omitempty"`
	Secret                *SecretVolumeSourceV1                `json:"secret,omitempty"`
	Storageos             *StorageOSVolumeSourceV1             `json:"storageos,omitempty"`
	VsphereVolume         *VsphereVirtualDiskVolumeSourceV1    `json:"vsphereVolume,omitempty"`
}
