// Code generated by pk8s; DO NOT EDIT.

package networking_gke_io

type ManagedCertificate struct {
	Spec   *ManagedCertificateSpec   `json:"spec,omitempty"`
	Status *ManagedCertificateStatus `json:"status,omitempty"`
}

type ManagedCertificateSpec struct {
	Domains []string `json:"domains,omitempty"`
}

type ManagedCertificateStatus struct {
	CertificateName   *string                                    `json:"certificateName,omitempty"`
	CertificateStatus *string                                    `json:"certificateStatus,omitempty"`
	DomainStatus      []ManagedCertificateStatusDomainStatusItem `json:"domainStatus,omitempty"`
	ExpireTime        *string                                    `json:"expireTime,omitempty"`
}

type ManagedCertificateStatusDomainStatusItem struct {
	Domain string `json:"domain"`
	Status string `json:"status"`
}

type ManagedCertificateList struct {
	Items []ManagedCertificate `json:"items"`
}
